services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
      - minio
    env_file:
      - .env.prod
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tournoi
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_PUBLIC_URL=http://minio:9000

  db:
    image: postgres:16
    container_name: tournoi
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: tournoi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 5;
        mc alias set local http://minio:9000 admin password &&
        mc mb -p local/avatars || true &&
        mc anonymous set download local/avatars
      "

volumes:
  db-data:
  minio-data:
