services:
  db:
    image: postgres
    container_name: tournoi
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tournoi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: