services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tournoi
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_PUBLIC_URL=http://minio:9000
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
      - NEXT_PUBLIC_BASE_URL=http://localhost:3000
      - JWT_SECRET=LeTournoiDesPeches2025
      - SMTP_HOST=smtp.resend.com
      - SMTP_PORT=587
      - SMTP_USER=resend
      - SMTP_PASS=re_Hj5N1nKU_DhCa8TTJDUNzsKZNGjP15QzH
      - SMTP_SECURE=false
    depends_on:
      - db
      - minio
    networks:
      - backend

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: tournoi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - miniodata:/data
    networks:
      - backend

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 5;
        mc alias set local http://minio:9000 minio minio123 &&
        mc mb -p local/avatars || true &&
        mc anonymous set download local/avatars
      "
    networks:
      - backend

volumes:
  pgdata:
  miniodata:

networks:
  backend:
