services:
  db:
    image: postgres
    container_name: tournoi
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tournoi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - data:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/tournoi

volumes:
  data: